server:
  port: 8080
  servlet:
    context-path: /SpringBootDemo

logging:
  config: classpath:log4j2.xml

user:
  order:
    queue:
      name: local.user.order.queue
    exchange:
      name: local.user.order.exchange
    routing:
      key:
        name: local.user.order.routing.key

mail:
  fromMail: AcronHYC@163.com
  queue:
    name: local.mail.queue
  exchange:
      name: local.mail.exchange
  routing:
      key:
        name: local.mail.routing.key

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10   #并发消费者的初始数量
        max-concurrency: 20   #并发消费者的最大数量
        prefetch: 5   #消费者每次监听可拉取的消息数量
  mail:
    host: smtp.163.com
    username: AcronHYC@163.com
    password: zxc123   #授权码
    default-encoding: UTF-8
    port: 25
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:  #线程安全的redis客户端；jedis:非线程安全，需要使用连接池为每个jedis实例分配一个连接
      pool:
        max-active: 8   #最大活跃链接数 默认8
        max-idle: 8   #最大空闲连接数 默认8
        min-idle: 0   #最大空闲连接数 默认8
        max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
    timeout: 3000     #连接超时时间 单位 ms（毫秒）
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springbootdemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:   #参考：https://blog.csdn.net/weixin_38187317/article/details/81562571
      initial-size: 5   #初始化大小
      min-idle: 5   #空闲连接池的大小
      maxActive: 20   #最大激活数量
      maxWait: 60000   #配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000   #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL   #用来检测连接是否有效的sql，要求是一个查询语句
      testWhileIdle: true   #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testOnBorrow: false   #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false   #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: true   #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      maxPoolPreparedStatementPerConnectionSize: 20   #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      filters: stat,wall,log4j2   #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000   #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      web-stat-filter:  #配置DruidStatFilter
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:  #配置DruidStatViewServlet
        url-pattern: "/druid/*"
        allow: 127.0.0.1,192.168.163.1   #IP白名单(没有配置或者为空，则允许所有访问)
        deny: 192.168.1.73   #IP黑名单 (存在共同时，deny优先于allow)
        reset-enable: false   #禁用HTML页面上的“Reset All”功能
        login-username: druid   #登录名
        login-password: 123456   #登录密码

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.acron.demo.entity
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler  #注解方式或IEnum接口使用该包
    map-underscore-to-camel-case: false    #取消驼峰模式
  type-enums-package: com.acron.demo.enums    #配置type-enums-package只对注解方式的枚举处理能提前加载缓存
  global-config:
    db-config:
      table-underline: false
      capital-mode: false
